### ISSUE TITLE
Capital letters across theme

### ISSUE THREAD

**Issue by aeonoea** [LinkStackOrg/minceraft#3]
Hi all,

thanks for the amazing theme! I only encountered one issue, which is that all the text across the theme is displayed in capitals / uppercase (tried on various browsers and with latest version of theme and linkstack).

In the preview of the theme letters are also lowercase, so there must be something wrong here. With other themes I don't have this issue. Is there something I missed in the config or elsewhere?

**Comment by aeonoea** [comment]
Update:

After tinkering around with the .tff files the issue seems to be that the mctxt.tff is not used at all, but only mctitle.tff across the theme. How to troubleshoot from here?

**Comment by lastsamurai26** [comment]
Yes, I see what you mean. 
Can you do me a favour and replace the following file?

minecraft/extra/custom-head.blade.php

[custom-head.blade.php.txt](https://github.com/user-attachments/files/16714326/custom-head.blade.php.txt)


please remove the txt from the file -> it should only be called custom-head.blade.php 

after that it should work

**Comment by aeonoea** [comment]
@lastsamurai26 That indeed did the trick. Thanks so much!
